<<<<<<< HEAD
# Generated by Django 2.2.24 on 2021-08-22 10:28
=======
<<<<<<< HEAD
# Generated by Django 3.2.6 on 2021-08-22 06:27
=======
# Generated by Django 2.2.24 on 2021-08-21 19:36
>>>>>>> 63cad427aec6909bb8a12626f78abde3c92fe3bd
>>>>>>> bb044d077c089c929be21995c658a898d4585f63

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
<<<<<<< HEAD
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
=======
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
>>>>>>> 63cad427aec6909bb8a12626f78abde3c92fe3bd
                ('notice_upload', models.ImageField(blank=True, null=True, upload_to='noticeUpload/')),
                ('description', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
<<<<<<< HEAD
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
=======
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
>>>>>>> 63cad427aec6909bb8a12626f78abde3c92fe3bd
                ('first_Name', models.CharField(max_length=50, verbose_name='first_Name')),
                ('last_Name', models.CharField(max_length=50, verbose_name='last_Name')),
                ('gender', models.CharField(max_length=5, verbose_name='gender')),
                ('age', models.CharField(max_length=3, verbose_name='age')),
                ('email_Id', models.CharField(max_length=20, unique=True, verbose_name='email_Id')),
                ('phone_Num', models.CharField(max_length=10, verbose_name='phone_Num')),
            ],
        ),
        migrations.CreateModel(
            name='Selected_person',
            fields=[
<<<<<<< HEAD
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.person')),
=======
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.Person')),
>>>>>>> 63cad427aec6909bb8a12626f78abde3c92fe3bd
            ],
        ),
    ]
