# Generated by Django 2.2.24 on 2021-08-12 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.CharField(max_length=3, verbose_name='age'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email_Id',
            field=models.CharField(max_length=20, verbose_name='email_Id'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(max_length=5, verbose_name='gender'),
        ),
    ]
