# Generated by Django 4.0.2 on 2022-03-11 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email_Id',
            field=models.CharField(max_length=50, verbose_name='email_Id'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(max_length=50, verbose_name='gender'),
        ),
    ]
