# Generated by Django 2.2.24 on 2021-08-21 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selected_person',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.Exam'),
        ),
        migrations.AlterField(
            model_name='selected_person',
            name='rooms_assigned',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.Rooms'),
        ),
    ]
