# Generated by Django 2.2.24 on 2021-08-22 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email_Id',
            field=models.CharField(max_length=20, verbose_name='email_Id'),
        ),
    ]
