# Generated by Django 4.0.2 on 2022-03-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_alter_person_email_id_alter_person_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phone_Num',
            field=models.CharField(max_length=100, verbose_name='phone_Num'),
        ),
    ]
