# Generated by Django 2.2.24 on 2021-08-21 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_auto_20210821_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selected_person',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='selected_person',
            name='rooms_assigned',
        ),
    ]
