# Generated by Django 3.2.6 on 2021-08-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_auto_20210822_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='description',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
