# Generated by Django 3.2.3 on 2021-06-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_Name', models.CharField(max_length=50)),
                ('middle_Name', models.CharField(max_length=50)),
                ('last_Name', models.CharField(max_length=50)),
                ('email_Id', models.EmailField(max_length=254, verbose_name='email_Id')),
                ('dob', models.DateField(verbose_name='dob')),
                ('phone_Num', models.CharField(max_length=10)),
                ('gender', models.BooleanField(verbose_name='gender')),
                ('field', models.CharField(max_length=15)),
                ('photo', models.ImageField(upload_to='', verbose_name='photo')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_Name', models.CharField(max_length=50)),
                ('middle_Name', models.CharField(max_length=50)),
                ('last_Name', models.CharField(max_length=50)),
                ('email_Id', models.EmailField(max_length=254, verbose_name='email_Id')),
                ('dob', models.DateField(verbose_name='dob')),
                ('phone_Num', models.CharField(max_length=10)),
                ('gender', models.BooleanField(verbose_name='gender')),
                ('qualification', models.CharField(max_length=50)),
                ('college', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='', verbose_name='photo')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_Name', models.CharField(max_length=50)),
                ('middle_Name', models.CharField(blank=True, max_length=50)),
                ('last_Name', models.CharField(max_length=50)),
                ('email_Id', models.EmailField(blank=True, max_length=254, verbose_name='email_Id')),
                ('dob', models.DateField(blank=True, verbose_name='dob')),
                ('phone_Num', models.CharField(max_length=10)),
                ('gender', models.BooleanField(blank=True, verbose_name='gender')),
                ('qualification', models.CharField(blank=True, max_length=50)),
                ('photo', models.ImageField(blank=True, upload_to='', verbose_name='photo')),
            ],
        ),
    ]
