# Generated by Django 3.2.3 on 2021-07-03 10:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='qualification',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='dob',
            field=models.DateField(verbose_name='dob'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email_Id',
            field=models.EmailField(max_length=254, verbose_name='email_Id'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='last_Name',
            field=models.CharField(max_length=50, verbose_name='last_Name'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='middle_Name',
            field=models.CharField(max_length=50, verbose_name='middle_Name'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone_Num',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='phone_Num'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(upload_to='', verbose_name='photo'),
        ),
    ]
