# Generated by Django 2.2.24 on 2021-07-03 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210703_1043'),
        ('account', '0002_auto_20210703_0605'),
    ]

    operations = [
    ]
