# Generated by Django 3.2.3 on 2021-07-03 11:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('T', 'Teacher'), ('S', 'Staff'), ('O', 'Other')], max_length=1, verbose_name='category')),
                ('first_Name', models.CharField(max_length=50)),
                ('middle_Name', models.CharField(max_length=50, verbose_name='middle_Name')),
                ('last_Name', models.CharField(max_length=50, verbose_name='last_Name')),
                ('email_Id', models.EmailField(max_length=254, verbose_name='email_Id')),
                ('dob', models.DateField(verbose_name='dob')),
                ('phone_Num', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='phone_Num')),
                ('photo', models.ImageField(upload_to='image_Uploads', verbose_name='photo')),
                ('college', models.CharField(max_length=20)),
            ],
        ),
    ]
