# Generated by Django 3.2.3 on 2021-08-07 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_auto_20210806_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, help_text=False, null=True, upload_to='image_Uploads', verbose_name='photo'),
        ),
    ]
