# Generated by Django 3.2.3 on 2021-06-26 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_auto_20210626_0604'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staffs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_Name', models.CharField(max_length=50)),
                ('middle_Name', models.CharField(max_length=50)),
                ('last_Name', models.CharField(max_length=50)),
                ('email_Id', models.EmailField(max_length=254, verbose_name='email_Id')),
                ('dob', models.DateTimeField(verbose_name='dob')),
                ('phone_Num', models.DecimalField(decimal_places=10, max_digits=10)),
                ('gender', models.BooleanField(verbose_name='gender')),
                ('field', models.CharField(max_length=15)),
                ('photo', models.ImageField(upload_to='', verbose_name='photo')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_Name', models.CharField(max_length=50)),
                ('middle_Name', models.CharField(max_length=50)),
                ('last_Name', models.CharField(max_length=50)),
                ('email_Id', models.EmailField(max_length=254, verbose_name='email_Id')),
                ('dob', models.DateTimeField(verbose_name='dob')),
                ('phone_Num', models.DecimalField(decimal_places=10, max_digits=10)),
                ('gender', models.BooleanField(verbose_name='gender')),
                ('qualification', models.CharField(max_length=50)),
                ('college', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='', verbose_name='photo')),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_Name', models.CharField(max_length=50)),
                ('middle_Name', models.CharField(max_length=50)),
                ('last_Name', models.CharField(max_length=50)),
                ('email_Id', models.EmailField(max_length=254, verbose_name='email_Id')),
                ('dob', models.DateTimeField(verbose_name='dob')),
                ('phone_Num', models.DecimalField(decimal_places=10, max_digits=10)),
                ('gender', models.BooleanField(verbose_name='gender')),
                ('qualification', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='', verbose_name='photo')),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
