# Generated by Django 3.2.3 on 2021-06-26 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_auto_20210626_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffs',
            name='dob',
            field=models.DateField(verbose_name='dob'),
        ),
        migrations.AlterField(
            model_name='students',
            name='dob',
            field=models.DateField(verbose_name='dob'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='dob',
            field=models.DateField(verbose_name='dob'),
        ),
    ]
