# Generated by Django 3.2.3 on 2021-06-26 07:06

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_auto_20210626_0656'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_Name', models.CharField(max_length=50)),
                ('middle_Name', models.CharField(max_length=50)),
                ('last_Name', models.CharField(max_length=50)),
                ('email_Id', models.EmailField(max_length=254, verbose_name='email_Id')),
                ('dob', models.DateField(verbose_name='dob')),
                ('phone_Num', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('gender', models.BooleanField(verbose_name='gender')),
                ('qualification', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='', verbose_name='photo')),
            ],
        ),
        migrations.RenameModel(
            old_name='Staffs',
            new_name='Staff',
        ),
        migrations.RenameModel(
            old_name='Students',
            new_name='Student',
        ),
        migrations.DeleteModel(
            name='Teachers',
        ),
    ]
