# Generated by Django 3.2.3 on 2021-06-26 07:27

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_auto_20210626_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='phone_Num',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
