# Generated by Django 3.2.3 on 2021-06-26 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0008_alter_teacher_phone_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='phone_Num',
        ),
    ]
