# Generated by Django 3.2.3 on 2021-06-26 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0009_remove_teacher_phone_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='email_Id',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='middle_Name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='qualification',
        ),
    ]
