# Generated by Django 3.2.3 on 2021-06-26 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0010_auto_20210626_0730'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
