# Generated by Django 2.2.24 on 2021-08-07 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='user_id',
        ),
    ]
