# Generated by Django 2.2.24 on 2021-08-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='time',
            field=models.CharField(max_length=30, verbose_name='time'),
        ),
    ]
