# Generated by Django 2.2.24 on 2021-08-07 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='title',
            field=models.CharField(choices=[('M', 'Masters'), ('B', 'Bachelors'), ('E', 'Entrance')], max_length=10),
        ),
    ]
