# Generated by Django 2.2.24 on 2021-08-22 14:57

import assigning.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduling', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('level', models.CharField(max_length=15)),
                ('manpower', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(max_length=30)),
                ('floor', models.CharField(max_length=30)),
                ('room_no', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assigning.Exam')),
                ('room_assigned', models.ManyToManyField(to='assigning.Rooms')),
                ('selected_persons', models.ManyToManyField(default=assigning.models.Selection.allpeople, to='scheduling.Selected_person')),
            ],
        ),
    ]
