# Generated by Django 2.2.24 on 2021-08-21 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        ('scheduling', '0002_auto_20210821_0945'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.Exam')),
                ('room_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.Rooms')),
                ('selected_persons', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.Person')),
            ],
        ),
    ]
