<<<<<<< HEAD
# Generated by Django 2.2.24 on 2021-08-22 05:52
=======
<<<<<<< HEAD
# Generated by Django 3.2.6 on 2021-08-22 06:27
=======
# Generated by Django 2.2.24 on 2021-08-21 19:36
>>>>>>> 63cad427aec6909bb8a12626f78abde3c92fe3bd
>>>>>>> bb044d077c089c929be21995c658a898d4585f63

import assigning.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduling', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
<<<<<<< HEAD
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
=======
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
>>>>>>> 63cad427aec6909bb8a12626f78abde3c92fe3bd
                ('date', models.DateField(verbose_name='date')),
                ('level', models.CharField(max_length=15)),
                ('manpower', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
<<<<<<< HEAD
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
=======
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
>>>>>>> 63cad427aec6909bb8a12626f78abde3c92fe3bd
                ('block', models.CharField(max_length=30)),
                ('floor', models.CharField(max_length=30)),
                ('room_no', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Selection',
            fields=[
<<<<<<< HEAD
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assigning.exam')),
=======
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assigning.Exam')),
<<<<<<< HEAD
                ('room_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assigning.Rooms')),
=======
>>>>>>> 63cad427aec6909bb8a12626f78abde3c92fe3bd
                ('room_assigned', models.ManyToManyField(to='assigning.Rooms')),
>>>>>>> bb044d077c089c929be21995c658a898d4585f63
                ('selected_persons', models.ManyToManyField(default=assigning.models.Selection.allpeople, to='scheduling.Selected_person')),
            ],
        ),
    ]
