# Generated by Django 2.2.24 on 2021-08-22 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assigning', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selection',
            name='room_assigned',
        ),
        migrations.AddField(
            model_name='selection',
            name='room_assigned',
            field=models.ManyToManyField(to='assigning.Rooms'),
        ),
    ]
