# Generated by Django 2.2.24 on 2021-08-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
        ('assigning', '0002_auto_20210821_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selection',
            name='room_assigned',
        ),
        migrations.AddField(
            model_name='selection',
            name='room_assigned',
            field=models.ManyToManyField(to='rooms.Rooms'),
        ),
    ]
