# Generated by Django 2.2.24 on 2021-08-22 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assigning', '0002_auto_20210822_0611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selection',
            name='room_assigned',
        ),
    ]
