# Generated by Django 3.2.6 on 2021-08-21 19:17

import assigning.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_auto_20210822_0057'),
        ('assigning', '0004_auto_20210821_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selection',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='selection',
            name='selected_persons',
            field=models.ManyToManyField(default=assigning.models.Selection.allpeople, to='scheduling.Selected_person'),
        ),
    ]
